### PR TITLE
tutorial fix

### PR DESCRIPTION
**Pull request by shijianjian**
Fixed tutorial bugs.

### CODE REVIEW

File: limbus/core/component.py [hunk 1]
```diff
@@ -125,12 +125,6 @@ def __init__(self, name: str):
         # Last execution to be run in the __call__ loop.
         self._stopping_iteration: int = 0  # 0 means run forever
 
-        # method called in _run_with_hooks to execute the component forward method
-        self._run_forward: Callable[..., Coroutine[Any, Any, ComponentState]] = self.forward
-        if nn.Module in Component.__mro__:
-            # If the component inherits from nn.Module, the forward method is called by the __call__ method
-            self._run_forward = nn.Module.__call__
-
```
Comment (shijianjian) [inline limbus/core/component.py]: The override does not work on my machine with Python 3.8. I therefore removed this part.

Comment (lferraz) [reply limbus/core/component.py]: with the change you did you are not running properly the forward. Pytorch is not only running the `forward` method when you run the __call__ method. 
what's the error you got? 
Anyway I will check it in a new env with 3.8.

Comment (lferraz) [reply limbus/core/component.py]: it works to me. Which pytorch version are you using? I am unsig 2.0.
anyway there is a bug here, addressed in a non-merged branch. If pytorch is not installed this will raise an exeption.

Comment (shijianjian) [reply limbus/core/component.py]: I got PyTorch 1.13 here. I do not think it is a pytorch issue, since it complains regarding the "self" parameter.

```
Traceback (most recent call last):
  File "C:\Users\SHIJ0C\git\limbus\limbus\core\component.py", line 335, in _run_with_hooks
    self.set_state(await self._run_forward(*args, **kwargs))
TypeError: _call_impl() missing 1 required positional argument: 'self'

INFO:limbus.core.component: printer0(1): STOPPED_AT_ITER
INFO:limbus.core.component: add(1): READY
ERROR:limbus.core.component:Error in component add.
Traceback (most recent call last):
  File "C:\Users\SHIJ0C\git\limbus\limbus\core\component.py", line 335, in _run_with_hooks
    self.set_state(await self._run_forward(*args, **kwargs))
TypeError: _call_impl() missing 1 required positional argument: 'self'

INFO:limbus.core.component: add(1): STOPPED_AT_ITER
INFO:limbus.core.pipeline: ENDED
```

Comment (lferraz) [reply limbus/core/component.py]: I could reproduce the error the error!!! I will check it now.

Comment (lferraz) [reply limbus/core/component.py]: Problem addressed, I forgot to pass the `self` param. The correct code there is:
```python
        try:
            if nn.Module in Component.__mro__:
                # If the component inherits from nn.Module, the forward method is called by the __call__ method
                self._run_forward = partial(nn.Module.__call__, self)
        except NameError:
            pass
```

remember to add `from functools import partial` at the top :)

If you want i can add the fix. Just let me know.

**Review by lferraz — APPROVED** [review]
